# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "hidePricePro-app"
client_id = "35b589f040f8516b3b9a0c407500535e"
application_url = "https://hidepricepro.test"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://hidepricepro.test/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "hidepricepro.myshopify.com"
